### ISSUE TITLE
Readability improvements

### ISSUE THREAD

**Issue by nunomaduro** [algolia/algoliasearch-client-php-helper#10]
On the class `NodeCollection`, the section bellow section is not clear, can you improve this? Maybe renaming properties or adding some comments.

Maybe improve class naming. `NodesCollection` <=> `NodeCollection`.

```php
    /**
     * Collection of \Algolia\AlgoliaSearch\Helper\Splitters\HtmlSplitter\Node.
     *
     * @var array<int, \Algolia\AlgoliaSearch\Helper\Splitters\HtmlSplitter\Node>
     */
    private $nodes = [];

    /**
     * @var \Algolia\AlgoliaSearch\Helper\Splitters\HtmlSplitter\NodesCollection
     */
    private $nodesCollection;
```

**Comment by TomKlotzPro** [comment]
Agree, but to be sync, don't forget that NodesCollection is a collection of NodeCollection which is a collection of Node. 
I think it could lead to misleading, I would prefer to improve class naming. WDYT ?
